
/* tslint:disable */
/**
* This file was automatically generated by json-to-ts.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run generate-schema-types.ts to regenerate this file.
*/
interface RootObject {
  type: string;
  properties: Properties;
  required: string[];
  additionalProperties: boolean;
}

interface Properties {
  tomtom: Tomtom;
  tomnum: Tomtom;
  tomdate: Tomdate;
  tomdefaultdate: Tomdefaultdate;
  tomcomplex: Tomcomplex;
}

interface Tomcomplex {
  anyOf: AnyOf[];
}

interface AnyOf {
  type: string;
  enum?: string[];
}

interface Tomdefaultdate {
  type: string;
  format: string;
  tsType: string;
  default: string;
}

interface Tomdate {
  type: string;
  format: string;
  tsType: string;
}

interface Tomtom {
  type: string;
  description: string;
  example: string;
}

declare const _default: RootObject;
export default _default;