#!/usr/bin/env -S npx ts-node
import { compile } from 'json-schema-to-typescript'
import fs from 'fs';
import _ from 'lodash';
import { JSONSchema4 } from 'json-schema';
import { recursiveListFilesInDirectory, listFilters } from './file-helper';
import path from 'path';

const schemaExtension = '.schema.json';
(async () => {
  const filePaths = await recursiveListFilesInDirectory('./src/validations/schemas', [], listFilters.endsWith(schemaExtension, true));
  const promises = filePaths.map(async (filePath) => {
    const dirname = path.dirname(filePath);
    const filename = path.basename(filePath, schemaExtension);
    const newPath = path.join(dirname, `${filename}.d.ts`);

    // TODO reference this script in the message
    await fs.promises.writeFile(newPath, `
  /* tslint:disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
    `);

    const schema = require(filePath) as JSONSchema4;
    const ts = await compile(schema, filename, {
      bannerComment: ''
    });
    await fs.promises.appendFile(newPath, ts + '\n');
  });
  await Promise.all(promises);
})();