
/* tslint:disable */
/**
* This file was automatically generated by json-to-ts.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run generate-schema-types.ts to regenerate this file.
*/
interface RootObject {
  '/courses/index': Coursesindex;
  '/courses/{id}': Coursesid;
  '/users/forgot-password': Coursesindex;
  '/users/impersonate': Usersimpersonate;
  '/test/{motmot}/{second}': Testmotmotsecond;
}

interface Testmotmotsecond {
  get: Post;
  post: Post;
}

interface Usersimpersonate {
  post: Post2;
}

interface Post2 {
  method: string;
  responseCodes: any[];
  requestSchemas: string[];
}

interface Coursesid {
  get: Post;
}

interface Coursesindex {
  post: Post;
}

interface Post {
  method: string;
  responseCodes: number[];
  requestSchemas: string[];
}

declare const _default: RootObject;
export default _default;