
/* tslint:disable */
/**
* This file was automatically generated by json-to-ts.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run generate-schema-types.ts to regenerate this file.
*/
interface RootObject {
  '/courses/index': Coursesindex;
  '/courses/{id}': Coursesindex;
  '/users/forgot-password': Coursesindex;
  '/users/impersonate': Coursesindex;
  '/test/{motmot}/{second}': Coursesindex;
}

interface Coursesindex {
  methods: string[];
}

declare const _default: RootObject;
export default _default;