
/* tslint:disable */
/**
* This file was automatically generated by json-to-ts.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run generate-schema-types.ts to regenerate this file.
*/
interface RootObject {
  description: string;
  externalDocs: ExternalDocs;
}

interface ExternalDocs {
  description: string;
  url: string;
}

declare const _default: RootObject;
export default _default;