
  /* tslint:disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
    export interface IBody {
  /**
   * The role that you intend to impersonate.
   */
  role: string | null;
}

export default IBody
