
/* tslint:disable */
/**
* This file was automatically generated by json-to-ts.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run generate-schema-types.ts to regenerate this file.
*/
interface RootObject {
  type: string;
  properties: Properties;
  required: string[];
  additionalProperties: boolean;
}

interface Properties {
  role: Role;
}

interface Role {
  type: string[];
  description: string;
  example?: any;
}

declare const _default: RootObject;
export default _default;