
/* tslint:disable */
/**
* This file was automatically generated by json-to-ts.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run generate-schema-types.ts to regenerate this file.
*/
interface RootObject {
  type: string;
  properties: Properties;
  required: string[];
  additionalProperties: boolean;
}

interface Properties {
  curriculumId: CurriculumId;
  name: Name;
  code: Name;
  start: Start;
  end: Start;
  sectionCode: Name;
  semesterCode: Name;
  textbooks: Name;
}

interface Start {
  type: string;
  format: string;
  'ts-type': string;
  description: string;
  example: string;
}

interface Name {
  type: string;
  description: string;
  example: string;
}

interface CurriculumId {
  type: string;
  description: string;
  example: number;
}

declare const _default: RootObject;
export default _default;