
  /* tslint:disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
    export interface IBody {
  /**
   * The curriculum this course is associated with.
   */
  curriculumId?: number;
  /**
   * The name of the new course.
   */
  name: string;
  /**
   * The code for the course.
   */
  code: string;
  /**
   * When the course is scheduled to start.
   */
  start: string;
  /**
   * When the course is scheduled to start.
   */
  end: string;
  /**
   * The code for this specific section of the course.
   */
  sectionCode: string;
  /**
   * The code for the semester this course takes place in.
   */
  semesterCode: string;
  /**
   * A text field for any textbook information you want to include.
   */
  textbooks: string;
}

export default IBody
